repos:
  - repo: local
    hooks:
      - id: pyright
        name: Pyright
        entry: uv run pyright
        language: system
        types: [python]
        pass_filenames: false # Ensures pyright uses pyrightconfig.json for the whole project scope
                              # pyright will check the entire project as configured.

      - id: ruff-check
        name: Ruff Check
        entry: uv run ruff check --fix --exit-non-zero-on-fix --force-exclude
        language: system
        types: [python]
        pass_filenames: true # Ruff will check and fix only the staged Python files.

      - id: ruff-format
        name: Ruff Format
        entry: uv run ruff format --force-exclude
        language: system
        types: [python]
        pass_filenames: true # Ruff will format only the staged Python files.
