name: Pre-commit Checks

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Set up uv
        uses: actions/setup-uv@v1

      - name: Install dependencies
        run: uv sync --frozen-lockfile # Ensures environment matches uv.lock

      - name: Run pre-commit
        run: uv run --locked pre-commit run --all-files
